import { useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { Layers, User, LogOut, CheckCircle } from 'lucide-react';
import SEO from './SEO';
import { GoogleLogin } from '@react-oauth/google';
import { jwtDecode } from "jwt-decode";
import Certificate from './Certificate';
import api from '../utils/api';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import Swal from 'sweetalert2';
import AOS from 'aos';
import 'aos/dist/aos.css';
import { useStudentAuth } from '../context/StudentAuthContext';

const registrationSchema = yup.object({
   fullName: yup.string().required("Full Name is required").min(3, "Name is too short"),
   branch: yup.string().required("Branch is required"),
   year: yup.string().required("Please select your year"),
   mobile: yup.string().required("Mobile number is required").matches(/^[0-9]{10}$/, "Must be exactly 10 digits"),
   college: yup.string().required("Institution name is required"),
}).required();

const StudentRegistration = () => {
   const navigate = useNavigate();
   const { login } = useStudentAuth();
   const [user, setUser] = useState(null);
   const [googleToken, setGoogleToken] = useState(null);
   const [registeredData, setRegisteredData] = useState(null);
   const [success, setSuccess] = useState(false);
   const [error, setError] = useState(null);

   const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm({
      resolver: yupResolver(registrationSchema)
   });

   useEffect(() => {
      AOS.init({ duration: 1000, once: true });
   }, []);

   const handleLoginSuccess = (credentialResponse) => {
      try {
         const decoded = jwtDecode(credentialResponse.credential);
         setUser(decoded);
         setGoogleToken(credentialResponse.credential);
         Swal.fire({
            title: 'Identity Verified',
            text: `Welcome, ${decoded.name}. Initializing credential portal.`,
            icon: 'success',
            background: '#ffffff',
            color: '#0f172a',
            customClass: { popup: 'rounded-[2rem] border border-slate-100 shadow-2xl' }
         });
      } catch (error) {
         Swal.fire('Identity Error', 'Token verification failed.', 'error');
      }
   };

   const handleLoginError = () => {
      Swal.fire('Error', 'Google sign-in failed.', 'error');
   };

   const handleLogout = () => {
      setUser(null);
      setSuccess(false);
      setRegisteredData(null);
      reset();
   }

   const onSubmit = async (data) => {
      try {
         const studentData = {
            ...data,
            email: user.email,
            profilePicture: user.picture
            // studentId is now generated by the backend for security and uniqueness
         };

         // Use api for consistent API calls
         const resData = await api.post('/api/certificate/register', studentData);

         if (resData) {
            setRegisteredData(resData.student);
            setSuccess(true);
            setTimeout(() => {
               handleAutoLogin();
            }, 3000);
         }
      } catch (err) {
         // Handle specific error messages from backend via the error response
         const errorMessage = err.response?.data?.message || err.message || "Registration failed.";
         const lowerError = errorMessage.toLowerCase();

         if (lowerError.includes("email") && (lowerError.includes("exists") || lowerError.includes("registered"))) {
            Swal.fire('Account Exists', 'This email is already registered. Please login instead.', 'warning');
         } else if (lowerError.includes("mobile") && (lowerError.includes("exists") || lowerError.includes("registered"))) {
            Swal.fire('Duplicate Mobile', 'This mobile number is already in use.', 'warning');
         } else {
            Swal.fire('Registration Error', errorMessage, 'error');
         }
      }
   };

   const handleAutoLogin = async () => {
      try {
         const data = await api.post('/api/student-auth/login', {
            token: googleToken
         });

         // Use context login
         login(data.student, data.token);
         navigate('/student-dashboard', { replace: true });
      } catch (loginErr) {
         navigate('/student-login');
      }
   };

   return (
      <div className="min-h-[calc(100vh-3.5rem)] md:min-h-[calc(100vh-4rem)] lg:min-h-[calc(100vh-5rem)] bg-[#f8fafc] flex items-center justify-center p-4 md:pb-8 md:px-8 relative overflow-hidden font-sans pt-14 md:pt-16 lg:pt-20">
         <SEO title="Registration - Piedocx" description="Student credential portal." />

         {/* Dynamic Background Elements */}
         <div className="absolute inset-0 overflow-hidden pointer-events-none">
            <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-100/40 rounded-full blur-[120px]"></div>
            <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-indigo-50/40 rounded-full blur-[120px]"></div>
            <div className="absolute inset-0 opacity-[0.02] bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
         </div>

         <div className="w-full max-w-6xl flex flex-col lg:flex-row bg-white rounded-[2.5rem] md:rounded-[4rem] overflow-hidden border border-slate-200 shadow-2xl relative z-10">

            {/* Left Panel: Brand Mission */}
            <div className="lg:w-[40%] bg-gradient-to-br from-blue-600 to-indigo-700 p-6 sm:p-10 md:p-16 flex flex-col justify-between text-white relative">
               <div className="absolute inset-0 opacity-10 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>

               <div className="relative z-10 space-y-12">
                  <div className="flex items-center gap-3">
                     <div className="p-3 bg-white/20 rounded-2xl backdrop-blur-md border border-white/10"><Layers size={24} /></div>
                     <span className="text-xl font-black tracking-widest uppercase italic">PIEDOCX</span>
                  </div>

                  <div className="space-y-6">
                     <h2 className="text-4xl md:text-5xl font-black leading-tight tracking-tight uppercase italic underline decoration-white/20 decoration-4 underline-offset-8">
                        Student <br />Enrollment <br />Portal.
                     </h2>
                     <p className="text-blue-50 text-lg font-medium leading-relaxed max-w-xs opacity-90">
                        Join our managed ecosystem to activate your academic credentials and track performance.
                     </p>
                  </div>

                  <div className="space-y-6">
                     {[
                        { label: 'Verified Identity', icon: '01' },
                        { label: 'Smart Indexing', icon: '02' },
                        { label: 'Rich Analytics', icon: '03' }
                     ].map((item, i) => (
                        <div key={i} className="flex items-center gap-6 group">
                           <span className="text-xs font-black text-blue-200/50 group-hover:text-white transition-colors uppercase font-mono">{item.icon}</span>
                           <div className="h-[1px] w-8 bg-white/20"></div>
                           <span className="text-sm font-bold tracking-widest uppercase group-hover:translate-x-2 transition-transform">{item.label}</span>
                        </div>
                     ))}
                  </div>
               </div>

               <div className="relative z-10 pt-10 border-t border-white/10">
                  <p className="text-[10px] font-black uppercase tracking-[0.3em] opacity-40">System Status: Secure</p>
               </div>
            </div>

            {/* Right Panel: Functional Core */}
            <div className="flex-1 p-6 sm:p-10 md:p-16 bg-white relative">
               {!user ? (
                  <div className="h-full flex flex-col items-center justify-center text-center space-y-10 max-w-sm mx-auto">
                     <div className="w-24 h-24 bg-slate-50 rounded-[2rem] border border-slate-200 flex items-center justify-center relative shadow-sm">
                        <User size={48} className="text-slate-300" />
                     </div>
                     <div className="space-y-4">
                        <h2 className="text-3xl font-black text-slate-900 italic uppercase tracking-tight leading-none">Identity Required</h2>
                        <p className="text-slate-500 font-medium leading-relaxed">
                           Please verify your identity using Google to access the student registration portal.
                        </p>
                     </div>
                     <div className="scale-110 transform hover:scale-115 transition-transform shadow-xl rounded-full">
                        <GoogleLogin
                           onSuccess={handleLoginSuccess}
                           onError={handleLoginError}
                           useOneTap
                           shape="pill"
                           theme="filled_blue"
                           size="large"
                        />
                     </div>
                  </div>
               ) : success ? (
                  <div className="h-full flex flex-col items-center justify-center text-center space-y-10 animate-scale-in">
                     <div className="w-24 h-24 bg-emerald-50 border border-emerald-100 rounded-full flex items-center justify-center relative">
                        <div className="absolute inset-0 bg-emerald-500 blur-[30px] opacity-10 animate-pulse"></div>
                        <CheckCircle className="text-emerald-500 w-12 h-12" />
                     </div>
                     <div className="space-y-4">
                        <h2 className="text-4xl font-black text-slate-900 italic uppercase">Sync Complete</h2>
                        <p className="text-slate-500 font-bold max-w-xs mx-auto">
                           Your profile is successfully registered. Redirecting to your command center...
                        </p>
                     </div>
                     <div className="flex gap-4">
                        <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce"></div>
                        <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce delay-100"></div>
                        <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce delay-200"></div>
                     </div>
                  </div>
               ) : (
                  <div className="space-y-10">
                     <div className="flex flex-col md:flex-row justify-between items-center gap-6 border-b border-slate-100 pb-6 md:pb-10">
                        <div className="flex items-center gap-5">
                           <div className="p-1 bg-slate-50 rounded-full border border-slate-200 shadow-sm">
                              <img src={user.picture} alt="Profile" className="w-14 h-14 rounded-full" />
                           </div>
                           <div>
                              <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest leading-none mb-1">Authenticated ID</p>
                              <p className="text-xl font-black text-slate-900 italic tracking-tight uppercase underline decoration-blue-600/20 underline-offset-4">{user.name}</p>
                           </div>
                        </div>
                        <button onClick={handleLogout} className="text-[10px] font-black text-red-500 uppercase tracking-widest bg-red-50 px-8 py-4 rounded-2xl border border-red-100 hover:bg-red-500 hover:text-white transition-all flex items-center gap-2 shadow-sm">
                           <LogOut size={16} /> Disconnect
                        </button>
                     </div>

                     <form className="grid grid-cols-1 md:grid-cols-2 gap-8" onSubmit={handleSubmit(onSubmit)}>
                        {[
                           { id: 'fullName', label: 'Student Full Name', placeholder: 'Legal full name', type: 'text' },
                           {
                              id: 'branch',
                              label: 'Field of Study',
                              type: 'select',
                              opts: [
                                 'Computer Science & Engineering (CSE)',
                                 'Information Technology (IT)',
                                 'Artificial Intelligence & Data Science (AI & DS)',
                                 'Electronics & Communication (ECE)',
                                 'Electrical Engineering (EE)',
                                 'Mechanical Engineering (ME)',
                                 'Civil Engineering',
                                 'Automobile Engineering',
                                 'Other'
                              ]
                           },
                           { id: 'year', label: 'Academic Year', type: 'select', opts: ['1st Year', '2nd Year', '3rd Year', '4th Year', 'Graduated'] },
                           { id: 'mobile', label: 'Mobile Number', placeholder: '+91 XXXXX XXXXX', type: 'tel' },
                           { id: 'college', label: 'Institution / College', placeholder: 'Your College Name', colSpan: true },
                        ].map((field, i) => (
                           <div key={i} className={field.colSpan ? 'md:col-span-2' : ''}>
                              <label className="block text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] mb-4 ml-1">{field.label}</label>
                              {field.type === 'select' ? (
                                 <select
                                    {...register(field.id)}
                                    className="w-full bg-slate-50 border border-slate-200 text-slate-900 font-bold rounded-[1.25rem] px-8 py-5 focus:outline-none focus:border-blue-600 focus:bg-white transition-all appearance-none shadow-sm"
                                 >
                                    <option value="">Select Option</option>
                                    {field.opts.map(opt => <option key={opt} value={opt}>{opt}</option>)}
                                 </select>
                              ) : (
                                 <input
                                    type={field.type}
                                    {...register(field.id)}
                                    placeholder={field.placeholder}
                                    className="w-full bg-slate-50 border border-slate-200 text-slate-900 font-bold rounded-[1.25rem] px-8 py-5 focus:outline-none focus:border-blue-600 focus:bg-white transition-all placeholder:text-slate-300 shadow-sm"
                                 />
                              )}
                              {errors[field.id] && <p className="text-[10px] text-red-500 font-black uppercase mt-3 ml-1 tracking-widest">{errors[field.id].message}</p>}
                           </div>
                        ))}

                        <div className="md:col-span-2 pt-10">
                           <button
                              type="submit"
                              disabled={isSubmitting}
                              className="w-full py-6 bg-slate-900 text-white rounded-[1.5rem] font-black text-sm uppercase italic tracking-[0.2em] transition-all hover:bg-blue-600 hover:shadow-2xl hover:shadow-blue-600/20 disabled:opacity-50 disabled:cursor-not-allowed active:scale-95 shadow-xl shadow-slate-900/10"
                           >
                              {isSubmitting ? 'Processing Registration...' : 'Complete Enrollment'}
                           </button>
                        </div>
                     </form>
                  </div>
               )}
            </div>
         </div>

         <style>{`
         @keyframes scale-in {
            0% { transform: scale(0.95); opacity: 0; }
            100% { transform: scale(1); opacity: 1; }
         }
         .animate-scale-in {
            animation: scale-in 0.6s cubic-bezier(0.23, 1, 0.32, 1) forwards;
         }
      `}</style>
      </div>
   );
};

export default StudentRegistration;
